spring:
  application:
    name: template-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
---
spring:
  cloud:
    config:
      label: main
  config:
    activate:
      on-profile: keycloak
    import: configserver:http://${CONFIG_SERVER_USERNAME:user}:${CONFIG_SERVER_PASSWORD:sa}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8099}?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100

---
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    config:
      enabled: false
  config:
    activate:
      on-profile: logger
logging:
  level:
    root: INFO
    io.openleap: DEBUG
eureka:
  client:
    enabled: false